package com.solarwinds.msp.ncentral.eventproduction.publisher.relay.grpc;

import com.google.common.util.concurrent.ListenableFuture;

import com.solarwinds.msp.relay.PublisherGrpc;
import com.solarwinds.msp.relay.Relay;

/**
 * This class represents the {@link PublisherGrpc.PublisherFutureStub} class wrapper.
 */
public class FuturePublisher {

    private final PublisherGrpc.PublisherFutureStub stub;

    /**
     * Creates an instance of this class with the specified {@link PublisherGrpc.PublisherFutureStub} object.
     *
     * @param stub the {@link PublisherGrpc.PublisherFutureStub} object to wrap.
     */
    public FuturePublisher(PublisherGrpc.PublisherFutureStub stub) {
        this.stub = stub;
    }

    /**
     * Publishes an event. Common errors generated by server conditions:
     * <pre>
     * INTERNAL - An internal error occurred, preventing the events from being relayed.
     * Likely a problem publishing the events to the event bus.
     * UNAUTHENTICATED - The token provided with this customer does not have authority to publish.
     * UNAVAILABLE - The service is not available, possibly because it is temporarily overloaded.
     * </pre>
     *
     * @param request the publish request.
     * @return The {@link ListenableFuture} with a publish response.
     */
    public ListenableFuture<Relay.PublishResponse> publish(Relay.PublishRequest request) {
        return stub.publish(request);
    }

    public PublisherGrpc.PublisherFutureStub getStub() {
        return stub;
    }
}
