cp ./libs/msp-relay-protobuf/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./sample/msp-relay-sample/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./sample/eventbus-configuration/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./sample/eventbus-client/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./api/entity/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./api/service/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./modules/producer/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./modules/converter/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./modules/publisher/msp-relay/targe/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./modules/controller/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp ./modules/persistence/file/target/*.jar ~/tmp/msprelayclient/DMSEventProducer/lib/.
cp sample/msp-relay-sample/target/event-sample-client-11.0.1-SNAPSHOT.jar ~/tmp/msprelayclient/DMSEventProducer/.
