#####     This is the main entity.  Everything derives form this.
# conversions:
#####               This is the name of the protobuf entity that is to be created.
#####               If it is a child entity of a parent then a link such as this should be used after the colon -> "&EntityName"
#     "EntityName":
#####                 This property must be included to point code to the fully qualified path of the protobuf class.
#         entityPath: "The.Fully.Qualified.Path.Of.The.Protobuf.Class"
#####             All tables capable of generating this entity are listed under this. This is mandatory for entities that are not children.
#         tables:
#             "EventTable1":
#####                  The table fields used by protocol buffer generation code follow this.
#                 joinToCustomer:
#####                  Any additional tables that the base table needs to join to in order to get to a customerId field.
#####                  Intermediary join tables can be aliased as anything. i.e. jointable1
#####                  The final table that contains the customerId needs to be aliased as "custTable"
#                 whereToCustomer:
#####                  These are the where criteria specific to the join criteria.
#####                  The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####                  " maintable.linkfield = custTable.linkfield "
#####                  If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#                 incrementalLoadDate:
#####                         The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#                 isTimeSeries: "false"
#####                         The default for this optional property is "false".
#####                         If you need to state otherwise, populate this entry with the value required.
#                 fields:
#####                         All fields that are required for protobuf generation need to be listed.
#####                         This is the name of the source field that is to be mapped.
#                     "sourcefield1":
#####                           The target field goes here.  Set a blank entry for the target field if the field is used but not mapped to a protobuf property.
#                         targetField: "Target1"
#####                           The default for this optional property is "false".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isMandatory: "false"
#####                           The default for this optional property is "true".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isTracked: "true"
#####     The table fields used by protocol buffer generation code follow this.
#####     This entry is for default fields used by all tables used to generate the protobuf class and to define mapped fields for child entities.
#         joinToCustomer:
#####             Any additional tables that the base table needs to join to in order to get to a customerId field.
#####             Intermediary join tables can be aliased as anything. i.e. jointable1
#####             The final table that contains the customerId needs to be aliased as "custTable"
#         whereToCustomer:
#####             These are the where criteria specific to the join criteria.
#####             The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####             " maintable.linkfield = custTable.linkfield "
#####             If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#         incrementalLoadDate:
#####             The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#         isTimeSeries: "false"
#####             The default for this optional property is "false".
#####             If you need to state otherwise, populate this entry with the value required.
#         fields:
#####             All fields that are required for protobuf generation need to be listed.
#####             This is the name of the source fied that is to be mapped. The same conditions and rules apply for these field properties as above.
#             "defaultsourcefield1":
#                 targetField: "Target2"
#                 isMandatory: "false"
#                 isTracked: "true"
#####             All child entities that are required for protobuf generation need to be listed here.
#         childEntities:
#####             The name of the child entity to be generated. *Note the astrix linking to the actual entity on this page.
#             - *ChildLink
conversions:
  "AvSecurity":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.AvSecurityOuterClass.AvSecurity"
    tables:
      "data20165_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "wmi20165_displayname":
            targetField: "Name"
            isMandatory: true
          "wmi20165_uptodate":
            targetField: "DefinitionsUpToDate"
          "wmi20165_scanningenabled":
            targetField: "ScanningEnabled"
          "wmi20165_versionnumber":
            targetField: "Version"
      "dataavdefenderstatus_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "avd_signature_age":
            targetField: "DefinitionsAge"
          "avd_protection_state":
            targetField: ""
          "avd_days_from_last_scan":
            targetField: "DaysFromLastScan"
          "avd_product_version":
            targetField: "Version"
      "dataendpointsecuritystatus_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "es_deffileage":
            targetField: "DefinitionsAge"
          "es_protectionstatus":
            targetField: ""
          "es_daysfromlastscan":
            targetField: "DaysFromLastScan"
          "es_agentversion":
            targetField: "Version"
      "databitdefenderstatus_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "bt_definitions_up_to_date":
            targetField: "DefinitionsUpToDate"
          "signature_age":
            targetField: "DefinitionsAge"
          "bt_scanning_enabled":
            targetField: "ScanningEnabled"
          "bt_days_from_last_scan":
            targetField: "DaysFromLastScan"
          "product_status_update_updatesigam":
            targetField: ""
          "bt_agent_version":
            targetField: ""
    fields:
      "taskid":
        targetField: "TaskId"
        isMandatory: true
      "scantime":
        targetField: "ScanTime"
        isTracked: false
      "errormessage":
        targetField: "ErrorMessage"
      "lastupdated":
        targetField: "LastUpdated"
        isMandatory: true
        isTracked: false
      "state":
        targetField: "StateId"
        isMandatory: true
  "AvSecurityThreat":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.AvSecurityThreatOuterClass.AvSecurityThreat"
    tables:
      "eventdata_malware":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "event_time":
            targetField: "EventTime"
            isMandatory: true
          "sequence":
            targetField: "Sequence"
          "threattype":
            targetField: "ThreatTypeId"
            isMandatory: true
          "threatname":
            targetField: "ThreatName"
            isMandatory: false
          "state":
            targetField: "StateId"
          "action":
            targetField: "ActionIds"
          "maltype":
            targetField: "MalwareTypeId"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
  "AvEventDataLocalization":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.AvEventDataLocalizationOuterClass.AvEventDataLocalization"
    tables:
      "eventdata_localization":
        incrementalLoadDate: ""
        fields:
          "tablename":
            targetField: ""
            isMandatory: true
          "language":
            targetField: "Language"
            isMandatory: true
          "field":
            targetField: ""
            isMandatory: true
          "property":
            targetField: "GenericValue"
            isMandatory: true
          "value":
            targetField: "Value"
            isMandatory: true
  "FirewallIncidents":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.FirewallIncidentsOuterClass.FirewallIncidents"
    tables:
      "datafwwatchguard_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "sfw_reg1count":
            targetField: "ErrorIncidents"
          "sfw_reg2count":
            targetField: "CriticalIncidents"
      "datafwsonicwall_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "sfs_reg1count":
            targetField: "EmergencyIncidents"
          "sfs_reg2count":
            targetField: "AlertIncidents"
          "sfs_reg3count":
            targetField: "ErrorIncidents"
          "sfs_reg4count":
            targetField: "WarningIncidents"
      "datafwciscopix_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "sfc_reg1count":
            targetField: "AlertIncidents"
          "sfc_reg2count":
            targetField: "CriticalIncidents"
          "sfc_reg3count":
            targetField: "ErrorIncidents"
          "sfc_reg4count":
            targetField: "WarningIncidents"
      "datafwnetscreen_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "sfn_reg1count":
            targetField: "EmergencyIncidents"
          "sfn_reg2count":
            targetField: "AlertIncidents"
          "sfn_reg3count":
            targetField: "CriticalIncidents"
          "sfn_reg4count":
            targetField: "ErrorIncidents"
          "sfn_reg5count":
            targetField: "WarningIncidents"
      "datafwfortigate_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "sff_reg1count":
            targetField: "EmergencyIncidents"
          "sff_reg2count":
            targetField: "AlertIncidents"
          "sff_reg3count":
            targetField: "CriticalIncidents"
          "sff_reg4count":
            targetField: "ErrorIncidents"
          "sff_reg5count":
            targetField: "WarningIncidents"
    fields:
      "taskid":
        targetField: "TaskId"
        isMandatory: true
      "scantime":
        targetField: "ScanTime"
        isTracked: false
      "errormessage":
        targetField: "ErrorMessage"
      "lastupdated":
        targetField: "LastUpdated"
        isMandatory: true
        isTracked: false
      "state":
        targetField: "StateId"
        isMandatory: true
