#####     This is the main entity.  Everything derives form this.
# conversions:
#####               This is the name of the protobuf entity that is to be created.
#####               If it is a child entity of a parent then a link such as this should be used after the colon -> "&EntityName"
#     "EntityName":
#####                 This property must be included to point code to the fully qualified path of the protobuf class.
#         entityPath: "The.Fully.Qualified.Path.Of.The.Protobuf.Class"
#####             All tables capable of generating this entity are listed under this. This is mandatory for entities that are not children.
#         tables:
#             "EventTable1":
#####                  The table fields used by protocol buffer generation code follow this.
#                 joinToCustomer:
#####                  Any additional tables that the base table needs to join to in order to get to a customerId field.
#####                  Intermediary join tables can be aliased as anything. i.e. jointable1
#####                  The final table that contains the customerId needs to be aliased as "custTable"
#                 whereToCustomer:
#####                  These are the where criteria specific to the join criteria.
#####                  The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####                  " maintable.linkfield = custTable.linkfield "
#####                  If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#                 incrementalLoadDate:
#####                         The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#                 isTimeSeries: "false"
#####                         The default for this optional property is "false".
#####                         If you need to state otherwise, populate this entry with the value required.
#                 fields:
#####                         All fields that are required for protobuf generation need to be listed.
#####                         This is the name of the source field that is to be mapped.
#                     "sourcefield1":
#####                           The target field goes here.  Set a blank entry for the target field if the field is used but not mapped to a protobuf property.
#                         targetField: "Target1"
#####                           The default for this optional property is "false".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isMandatory: "false"
#####                           The default for this optional property is "true".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isTracked: "true"
#####     The table fields used by protocol buffer generation code follow this.
#####     This entry is for default fields used by all tables used to generate the protobuf class and to define mapped fields for child entities.
#         joinToCustomer:
#####             Any additional tables that the base table needs to join to in order to get to a customerId field.
#####             Intermediary join tables can be aliased as anything. i.e. jointable1
#####             The final table that contains the customerId needs to be aliased as "custTable"
#         whereToCustomer:
#####             These are the where criteria specific to the join criteria.
#####             The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####             " maintable.linkfield = custTable.linkfield "
#####             If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#         incrementalLoadDate:
#####             The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#         isTimeSeries: "false"
#####             The default for this optional property is "false".
#####             If you need to state otherwise, populate this entry with the value required.
#         fields:
#####             All fields that are required for protobuf generation need to be listed.
#####             This is the name of the source fied that is to be mapped. The same conditions and rules apply for these field properties as above.
#             "defaultsourcefield1":
#                 targetField: "Target2"
#                 isMandatory: "false"
#                 isTracked: "true"
#####             All child entities that are required for protobuf generation need to be listed here.
#         childEntities:
#####             The name of the child entity to be generated. *Note the astrix linking to the actual entity on this page.
#             - *ChildLink
conversions:
  "BackupStatus": &BackupStatus
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.BackupOuterClass.Backup.BackupStatus"
    fields:
      "job_stat":
        targetField: ""
      "backup_status":
        targetField: ""
      "event_status":
        targetField: ""
      "nable_backup_status":
        targetField: ""
      "max_backup_status":
        targetField: ""
      "ampwblasterrorstatus":
        targetField: ""
      "ampvsjmjobresultstatus":
        targetField: ""
      "ampvjmjobresultstatus":
        targetField: ""
  "Backup":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.BackupOuterClass.Backup"
    tables:
      "databackupdetails_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "protected_size":
            targetField: "TotalBytesProcessed"
          "backup_duration":
            targetField: ""
          "backup_status_desc":
            targetField: "ErrorStatus"
          "last_backup":
            targetField: "JobStart"
          "backup_status":
            targetField: ""
      "databackupexec_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "byte_rate":
            targetField: "ByteRate"
          "total_bytes":
            targetField: "TotalBytesProcessed"
          "err_stat":
            targetField: "ErrorStatus"
          "job_name":
            targetField: "Description"
          "start_time":
            targetField: "JobStart"
          "end_time":
            targetField: "JobEnd"
          "job_stat":
            targetField: ""
      "databackupmanagerevents_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "event_job_size":
            targetField: "TotalBytesProcessed"
          "event_status_desc":
            targetField: ""
          "event_job_name":
            targetField: "Description"
          "event_job_date":
            targetField: ""
          "event_status":
            targetField: ""
      "datamaxbackupstatus_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "max_plugin":
            targetField: "Description"
          "max_processed_size":
            targetField: ""
          "max_session_duration":
            targetField: ""
          "max_backup_status_desc":
            targetField: "ErrorStatus"
          "max_backup_end_time":
            targetField: "JobEnd"
          "max_backup_inprogress":
            targetField: ""
          "max_backup_status":
            targetField: ""
      "datanablebackupdetails_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "nable_backup_size":
            targetField: ""
          "nable_backup_duration":
            targetField: ""
          "nable_backup_status_detail":
            targetField: "ErrorStatus"
          "nable_backup_start_time":
            targetField: "JobStart"
          "nable_backup_status":
            targetField: ""
      "datastveeamjobmonitor_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "ampvjmjobname":
            targetField: "Description"
          "ampvjmbackupsize":
            targetField: ""
          "ampvjmduration":
            targetField: ""
          "ampvjmjobresult":
            targetField: ""
          "ampvjmstarttime":
            targetField: "JobStart"
          "ampvjmendtime":
            targetField: "JobEnd"
          "ampvjmjobid":
            targetField: ""
          "ampvjmjobresultstatus":
            targetField: ""
      "datastveeamsuremonitor_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "ampvsjmjobname":
            targetField: "Description"
          "ampvsjmjobresult":
            targetField: ""
          "ampvsjmjobstart":
            targetField: "JobStart"
          "ampvsjmjobendtime":
            targetField: "JobEnd"
          "ampvsjmjobid":
            targetField: ""
          "ampvsjmjobresultstatus":
            targetField: ""
          "ampvsjmjobduration":
            targetField: ""
      "datastwindowsbackup_detailed":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        isTimeSeries: true
        fields:
          "ampwblastbackuptarget":
            targetField: "Description"
          "ampwblasterrordescription":
            targetField: ""
          "ampwblastbackuptime":
            targetField: ""
          "ampwblasterrorstatus":
            targetField: ""
    fields:
      "taskid":
        targetField: "TaskId"
        isMandatory: true
      "scantime":
        targetField: "ScanTime"
        isTracked: false
      "errormessage":
        targetField: ""
      "lastupdated":
        targetField: "LastUpdated"
        isMandatory: true
        isTracked: false
      "state":
        targetField: "StateId"
        isMandatory: true
    childEntities:
      - *BackupStatus
