#####     This is the main entity.  Everything derives form this.
# conversions:
#####               This is the name of the protobuf entity that is to be created.
#####               If it is a child entity of a parent then a link such as this should be used after the colon -> "&EntityName"
#     "EntityName":
#####                 This property must be included to point code to the fully qualified path of the protobuf class.
#         entityPath: "The.Fully.Qualified.Path.Of.The.Protobuf.Class"
#####             All tables capable of generating this entity are listed under this. This is mandatory for entities that are not children.
#         tables:
#             "EventTable1":
#####                  The table fields used by protocol buffer generation code follow this.
#                 joinToCustomer:
#####                  Any additional tables that the base table needs to join to in order to get to a customerId field.
#####                  Intermediary join tables can be aliased as anything. i.e. jointable1
#####                  The final table that contains the customerId needs to be aliased as "custTable"
#                 whereToCustomer:
#####                  These are the where criteria specific to the join criteria.
#####                  The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####                  " maintable.linkfield = custTable.linkfield "
#####                  If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#                 incrementalLoadDate:
#####                         The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#                 isTimeSeries: "false"
#####                         The default for this optional property is "false".
#####                         If you need to state otherwise, populate this entry with the value required.
#                 fields:
#####                         All fields that are required for protobuf generation need to be listed.
#####                         This is the name of the source field that is to be mapped.
#                     "sourcefield1":
#####                           The target field goes here.  Set a blank entry for the target field if the field is used but not mapped to a protobuf property.
#                         targetField: "Target1"
#####                           The default for this optional property is "false".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isMandatory: "false"
#####                           The default for this optional property is "true".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isTracked: "true"
#####     The table fields used by protocol buffer generation code follow this.
#####     This entry is for default fields used by all tables used to generate the protobuf class and to define mapped fields for child entities.
#         joinToCustomer:
#####             Any additional tables that the base table needs to join to in order to get to a customerId field.
#####             Intermediary join tables can be aliased as anything. i.e. jointable1
#####             The final table that contains the customerId needs to be aliased as "custTable"
#         whereToCustomer:
#####             These are the where criteria specific to the join criteria.
#####             The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####             " maintable.linkfield = custTable.linkfield "
#####             If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#         incrementalLoadDate:
#####             The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#         isTimeSeries: "false"
#####             The default for this optional property is "false".
#####             If you need to state otherwise, populate this entry with the value required.
#         fields:
#####             All fields that are required for protobuf generation need to be listed.
#####             This is the name of the source fied that is to be mapped. The same conditions and rules apply for these field properties as above.
#             "defaultsourcefield1":
#                 targetField: "Target2"
#                 isMandatory: "false"
#                 isTracked: "true"
#####             All child entities that are required for protobuf generation need to be listed here.
#         childEntities:
#####             The name of the child entity to be generated. *Note the astrix linking to the actual entity on this page.
#             - *ChildLink
conversions:
  "ServiceType": &ServiceType
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.ServiceTypeOuterClass.ServiceType"
    fields:
      "serviceitemtypeid":
        targetField: "ServiceTypeId"
    tables:
      "serviceitemtype":
        fields:
          "description":
            targetField: "Name"
  "ServiceInstanceType": &ServiceInstanceType
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.ServiceInstanceTypeOuterClass.ServiceInstanceType"
    fields:
      "servicetype":
        targetField: "Name"
    tables:
      "servicetype":
        fields:
          "servicetypeid":
            targetField: "ServiceInstanceTypeId"
          "description":
            targetField: "Description"
          "isgenericserviceengine":
            targetField: "GenericServiceEngine"
  "Service":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.ServiceOuterClass.Service"
    tables:
      "serviceitem":
        fields:
          "serviceitemid":
            targetField: "ServiceId"
            isMandatory: true
          "customerid":
            targetField: "ClientId"
            isMandatory: true
          "displayname":
            targetField: "Name"
            isMandatory: true
          "description":
            targetField: "Description"
          "isavailability":
            targetField: "IsAvailability"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
    childEntities:
      - *ServiceType
  "ServiceInstance":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.ServiceInstanceOuterClass.ServiceInstance"
    tables:
      "service":
        fields:
          "serviceid":
            targetField: "ServiceInstanceId"
            isMandatory: true
          "serviceitemid":
            targetField: "ServiceId"
            isMandatory: false
          "displayname":
            targetField: "Name"
            isMandatory: true
          "description":
            targetField: "Description"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
    childEntities:
      - *ServiceInstanceType
  "Task":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.TaskOuterClass.Task"
    tables:
      "appliancetask":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "taskid":
            targetField: "TaskId"
            isMandatory: true
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "taskstatus":
            targetField: "StatusId"
            isMandatory: true
          "taskstate":
            targetField: "StateId"
            isMandatory: true
          "serviceid":
            targetField: "ServiceInstanceId"
            isMandatory: true
          "taskident":
            targetField: "Name"
          "tasknote":
            targetField: "Note"
            isMandatory: false
          "created":
            targetField: "Created"
            isMandatory: true
          "deleted":
            targetField: "Deleted"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
  "TaskParameters":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.TaskParametersOuterClass.TaskParameters"
    tables:
      "parameters":
        joinToCustomer: " appliancetask jointable1, device custTable "
        whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
        fields:
          "taskid":
            targetField: "TaskId"
            isMandatory: true
          "pkey":
            targetField: "ParameterKey"
            isMandatory: true
          "pvalue":
            targetField: "ParameterValue"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "GenericServiceDataType":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.GenericServiceDataTypeOuterClass.GenericServiceDataType"
    tables:
      "cooked_type":
        incrementalLoadDate: ""
        fields:
          "name":
            targetField: "Name"
            isMandatory: true
          "cookid":
            targetField: "DataTypeId"
            isMandatory: true
          "ctmin":
            targetField: "MinValue"
            isMandatory: true
          "ctmax":
            targetField: "MaxValue"
            isMandatory: true
          "cim_type":
            targetField: "CimType"
            isMandatory: true
  "GenericServiceDestination":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.GenericServiceDestinationOuterClass.GenericServiceDestination"
    tables:
      "servicecategoryproperties":
        joinToCustomer: " serviceitem custTable "
        whereToCustomer: " maintable.serviceitemid = custTable.serviceitemid "
        fields:
          "serviceitemid":
            targetField: "ServiceId"
            isMandatory: true
          "dbtable":
            targetField: "TableName"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "GenericServiceScanDetail":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.GenericServiceScanDetailOuterClass.GenericServiceScanDetail"
    tables:
      "scandetail":
        joinToCustomer: " serviceitem custTable "
        whereToCustomer: " maintable.serviceitemid = custTable.serviceitemid "
        fields:
          "scandetailid":
            targetField: "GenericServiceScanDetailId"
            isMandatory: true
          "serviceitemid":
            targetField: "ServiceId"
            isMandatory: true
          "cookid":
            targetField: "DataTypeId"
            isMandatory: true
          "detailname":
            targetField: "DetailName"
            isMandatory: true
          "detaildesc":
            targetField: "DetailDescription"
          "scale":
            targetField: "Scale"
          "unit":
            targetField: "Unit"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "GenericServiceData":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.GenericServiceDataOuterClass.GenericServiceData"
    joinToCustomer: " appliancetask jointable1, device custTable "
    whereToCustomer: " maintable.taskid = jointable1.taskid and jointable1.deviceid = custTable.deviceid "
    isTimeSeries: true
    fields:
      "taskid":
        targetField: "TaskId"
        isMandatory: true
      "scantime":
        targetField: "ScanTime"
        isTracked: false
      "errormessage":
        targetField: "ErrorMessage"
      "lastupdated":
        targetField: "LastUpdated"
        isMandatory: true
        isTracked: false
      "state":
        targetField: "StateId"
        isMandatory: true
  "Status":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.StatusOuterClass.Status"
    tables:
      "taskstatestatuspriority":
        fields:
          "taskstatus":
            targetField: "StatusId"
          "statusdesc":
            targetField: "Name"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "State":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.StateOuterClass.State"
    tables:
      "taskstatestatuspriority":
        fields:
          "taskstate":
            targetField: "StateId"
          "statedesc":
            targetField: "Name"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "TaskThreshold":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.TaskThresholdOuterClass.TaskThreshold"
    tables:
      "threshold":
        joinToCustomer: " appliancetask jointtbl1, device custTable "
        whereToCustomer: " maintable.taskid = jointtbl1.taskid and jointtbl1.deviceid = custTable.deviceid "
        fields:
          "taskid":
            targetField: "TaskId"
            isMandatory: true
          "scandetailid":
            targetField: "GenericServiceScanDetailId"
            isMandatory: true
          "valuelow":
            targetField: "MinValue"
          "valuehigh":
            targetField: "MaxValue"
          "taskstate":
            targetField: "StateId"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
