#####     This is the main entity.  Everything derives form this.
# conversions:
#####               This is the name of the protobuf entity that is to be created.
#####               If it is a child entity of a parent then a link such as this should be used after the colon -> "&EntityName"
#     "EntityName":
#####                 This property must be included to point code to the fully qualified path of the protobuf class.
#         entityPath: "The.Fully.Qualified.Path.Of.The.Protobuf.Class"
#####             All tables capable of generating this entity are listed under this. This is mandatory for entities that are not children.
#         tables:
#             "EventTable1":
#####                  The table fields used by protocol buffer generation code follow this.
#                 joinToCustomer:
#####                  Any additional tables that the base table needs to join to in order to get to a customerId field.
#####                  Intermediary join tables can be aliased as anything. i.e. jointable1
#####                  The final table that contains the customerId needs to be aliased as "custTable"
#                 whereToCustomer:
#####                  These are the where criteria specific to the join criteria.
#####                  The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####                  " maintable.linkfield = custTable.linkfield "
#####                  If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#                 incrementalLoadDate:
#####                         The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#                 isTimeSeries: "false"
#####                         The default for this optional property is "false".
#####                         If you need to state otherwise, populate this entry with the value required.
#                 fields:
#####                         All fields that are required for protobuf generation need to be listed.
#####                         This is the name of the source field that is to be mapped.
#                     "sourcefield1":
#####                           The target field goes here.  Set a blank entry for the target field if the field is used but not mapped to a protobuf property.
#                         targetField: "Target1"
#####                           The default for this optional property is "false".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isMandatory: "false"
#####                           The default for this optional property is "true".
#####                           If you need to state otherwise, populate this entry with the value required.
#                         isTracked: "true"
#####     The table fields used by protocol buffer generation code follow this.
#####     This entry is for default fields used by all tables used to generate the protobuf class and to define mapped fields for child entities.
#         joinToCustomer:
#####             Any additional tables that the base table needs to join to in order to get to a customerId field.
#####             Intermediary join tables can be aliased as anything. i.e. jointable1
#####             The final table that contains the customerId needs to be aliased as "custTable"
#         whereToCustomer:
#####             These are the where criteria specific to the join criteria.
#####             The base table is always aliased as "mainTable" int the case of a single simple join the where criteria would be as follows:
#####             " maintable.linkfield = custTable.linkfield "
#####             If there are multiple joins you would as those as well. i.e. " maintable.linkfield = jointable1.linkfield and jointable1.anotherlinkfield = custTable.anotherlinkfield "
#         incrementalLoadDate:
#####             The field name for the column to be used for incremental data loads when scraping data.  The default is "lastupdated"
#         isTimeSeries: "false"
#####             The default for this optional property is "false".
#####             If you need to state otherwise, populate this entry with the value required.
#         fields:
#####             All fields that are required for protobuf generation need to be listed.
#####             This is the name of the source fied that is to be mapped. The same conditions and rules apply for these field properties as above.
#             "defaultsourcefield1":
#                 targetField: "Target2"
#                 isMandatory: "false"
#                 isTracked: "true"
#####             All child entities that are required for protobuf generation need to be listed here.
#         childEntities:
#####             The name of the child entity to be generated. *Note the astrix linking to the actual entity on this page.
#             - *ChildLink
conversions:
  "Application": &Application
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.ApplicationOuterClass.Application"
    fields:
      "displayname":
        targetField: "Name"
      "applicationname":
        targetField: "Name"
      "publisher":
        targetField: "Publisher"
        isMandatory: false
      "version":
        targetField: "Version"
        isMandatory: false
  "PatchCategory": &PatchCategory
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.PatchCategoryOuterClass.PatchCategory"
    tables:
      "patch_classification":
        fields:
          "guid":
            targetField: "sourceId"
            isMandatory: true
          "classificationname":
            targetField: "Name"
  "DeviceLogins":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.DeviceLoginsOuterClass.DeviceLogins"
    tables:
      "cim_custom_lastloggedinuser":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
          "username":
            targetField: "UserName"
            isMandatory: true
          "userdomain":
            targetField: "Domain"
          "stillloggedin":
            targetField: "StillLoggedIn"
  "OperatingSystem":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.OperatingSystemOuterClass.OperatingSystem"
    tables:
      "cim_operatingsystem":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
          "supportedos":
            targetField: "Type"
            isMandatory: true
          "reportedos":
            targetField: "Name"
            isMandatory: true
          "version":
            targetField: "Version"
          "servicepackmajor":
            targetField: "ServicePackMajor"
          "servicepackminor":
            targetField: "ServicePackMinor"
          "licensekey":
            targetField: "ProductKey"
          "installdate":
            targetField: "InstallDate"
          "lastbootuptime":
            targetField: "LastBootTime"
          "timesystemup":
            targetField: "TimeSystemUp"
  "Patch":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.PatchOuterClass.Patch"
    tables:
      "patch":
        incrementalLoadDate: "publisheddate"
        fields:
          "patchguid":
            targetField: "PatchGUID"
            isMandatory: true
          "title":
            targetField: "Name"
            isMandatory: true
          "description":
            targetField: "Description"
          "kbnumbers":
            targetField: "KbNumber"
          "infourls":
            targetField: "InfoURLs"
          "languagessupported":
            targetField: "LanguagesSupported"
          "products":
            targetField: "Products"
          "severity":
            targetField: ""
            isMandatory: true
          "classification":
            targetField: ""
            isMandatory: false
          "publisheddate":
            targetField: "PublishDate"
            isMandatory: true
    childEntities:
      - *PatchCategory
  "PatchProduct":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.entity.PatchProductOuterClass.PatchProduct"
    tables:
      "patch_product":
        fields:
          "name":
            targetField: "name"
            isMandatory: true
          "id":
            targetField: "sourceId"
            isMandatory: true
          "parentid":
            targetField: "parentSourceId"
            isMandatory: true
  "PatchAction":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.PatchActionOuterClass.PatchAction"
    tables:
      "cim_patch":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
          "installationresult":
            targetField: "ActionStatus"
            isMandatory: true
          "installeddate":
            targetField: "ActionDate"
          "updateid":
            targetField: "PatchId"
            isMandatory: true
      "patchapprovallog":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: false
          "date":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: false
          "patchguid":
            targetField: "PatchId"
            isMandatory: true
          "status":
            targetField: "ActionStatus"
            isMandatory: true
  "SharedFolders":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.SharedFoldersOuterClass.SharedFolders"
    tables:
      "cim_folderforshare":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "sharename":
            targetField: "ShareName"
            isMandatory: true
          "path":
            targetField: "Path"
            isMandatory: false
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "MappedDrive":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.MappedDriveOuterClass.MappedDrive"
    tables:
      "cim_mappeddrive":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "drivename":
            targetField: "DriveName"
            isMandatory: true
          "remotepath":
            targetField: "RemotePath"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "PageFile":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.PageFileOuterClass.PageFile"
    tables:
      "cim_pagefile":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "filename":
            targetField: "FileName"
            isMandatory: true
          "filesize":
            targetField: "FileSizeBytes"
            isMandatory: true
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "SystemService":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.SystemServiceOuterClass.SystemService"
    tables:
      "cim_service":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
          "caption":
            targetField: "Caption"
          "executablename":
            targetField: "ExecutableName"
            isMandatory: true
          "servicename":
            targetField: "ServiceName"
            isMandatory: true
          "startuptype":
            targetField: "StartupType"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
  "ApplicationLicenseCompliance":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.tasks.ApplicationLicenseComplianceOuterClass.ApplicationLicenseCompliance"
    tables:
      "licensecompliance":
        fields:
          "customerid":
            targetField: "ClientId"
            isMandatory: true
          "licenses":
            targetField: "licenses"
          "instances":
            targetField: "instances"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
    childEntities:
      - *Application
  "ApplicationStatus":
    entityPath: "com.solarwinds.msp.ncentral.proto.entity.asset.ApplicationStatusOuterClass.ApplicationStatus"
    tables:
      "cim_application":
        joinToCustomer: " device custTable "
        whereToCustomer: " maintable.deviceid = custTable.deviceid "
        fields:
          "licensekey":
            targetField: "LicenseKey"
          "licensetype":
            targetField: "LicenseType"
          "productid":
            targetField: "ProductId"
          "installationdate":
            targetField: "InstallationDate"
          "lastupdated":
            targetField: "LastUpdated"
            isMandatory: true
            isTracked: false
          "deleted":
            targetField: "Deleted"
            isMandatory: true
          "deviceid":
            targetField: "DeviceId"
            isMandatory: true
    childEntities:
      - *Application
